-- Shaman totem looks: a look per totem element, shown in place of the race's stock totem. They
-- share the druid forms' tables: mod_transmog_plus_forms rows with Form 'fire', 'earth', 'water'
-- or 'air' (in mod_transmog_plus_form_choice: 7 fire, 8 earth, 9 water, 10 air). The rows
-- themselves are in mod_transmog_plus_2026_10_10_totems_data.sql, generated by
-- buildthehomelab/wow-mod-retail-druid-forms tools (build_patch.py --pack totems), which also
-- build the client patch with the retail totem models (patch-V).
DELETE FROM `module_string` WHERE `module` = 'mod-transmog-plus' AND `id` = 25;
INSERT INTO `module_string` (`module`, `id`, `string`) VALUES
('mod-transmog-plus', 25, 'new totem looks unlocked. Pick them in the Totems tab of the Transmogrify window (/transmog).');
